stages:
  load_data:
    cmd: python parkinson/load_data_v2.py ${data.filepath} ${data.processed}train_test_data.csv
    deps:
      - parkinson/load_data_v2.py
      - ${data.filepath}
    outs:
      - ${data.processed}train_test_data.csv

  preprocess:
    cmd: python parkinson/preprocess_data_v2.py ${data.processed}train_test_data.csv ${data.processed}X_train.csv ${data.processed}X_test.csv ${data.processed}y_train.csv ${data.processed}y_test.csv
    deps:
      - parkinson/preprocess_data_v2.py
      - ${data.processed}train_test_data.csv
    outs:
      - ${data.processed}X_train.csv
      - ${data.processed}X_test.csv
      - ${data.processed}y_train.csv
      - ${data.processed}y_test.csv

  train_GradientBoostingRegressor:
    cmd: python parkinson/train_v2.py data/processed/X_train.csv data/processed/X_test.csv data/processed/y_train.csv data/processed/y_test.csv GradientBoostingRegressor
    deps:
      - parkinson/train_v2.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/GradientBoostingRegressor_model.pkl

  train_RandomForestRegressor:
    cmd: python parkinson/train_v2.py data/processed/X_train.csv data/processed/X_test.csv data/processed/y_train.csv data/processed/y_test.csv RandomForestRegressor
    deps:
      - parkinson/train_v2.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/RandomForestRegressor_model.pkl

  evaluate_GradientBoostingRegressor:
    cmd: python parkinson/evaluate_v2.py models/GradientBoostingRegressor_model.pkl data/processed/X_test.csv data/processed/y_test.csv reports/GradientBoostingRegressor.txt
    deps:
      - parkinson/evaluate_v2.py
      - models/GradientBoostingRegressor_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/GradientBoostingRegressor.txt


  evaluate_RandomForestRegressor:
    cmd: python parkinson/evaluate_v2.py models/RandomForestRegressor_model.pkl data/processed/X_test.csv data/processed/y_test.csv reports/RandomForestRegressor.txt
    deps:
      - parkinson/evaluate_v2.py
      - models/RandomForestRegressor_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/RandomForestRegressor.txt
