stages:
  load_data:
    cmd: python parkinson/load_data.py ${data.filepath} ${data.processed}train_test_data.csv
    deps:
      - parkinson/load_data.py
      - ${data.filepath}
    outs:
      - ${data.processed}train_test_data.csv

  preprocess:
    cmd: python parkinson/preprocess_data.py ${data.processed}train_test_data.csv ${data.processed}X_train.csv ${data.processed}X_test.csv ${data.processed}y_train.csv ${data.processed}y_test.csv
    deps:
      - parkinson/preprocess_data.py
      - ${data.processed}train_test_data.csv
    outs:
      - ${data.processed}X_train.csv
      - ${data.processed}X_test.csv
      - ${data.processed}y_train.csv
      - ${data.processed}y_test.csv

  train:
    cmd: python parkinson/train.py ${data.processed}X_train.csv ${data.processed}y_train.csv ${data.models}model.pkl
    deps:
      - parkinson/train.py
      - ${data.processed}X_train.csv
      - ${data.processed}y_train.csv
    outs:
      - ${data.models}model.pkl

  evaluate:
    cmd: python parkinson/evaluate.py ${data.models}model.pkl ${data.processed}X_test.csv ${data.processed}y_test.csv
    deps:
      - parkinson/evaluate.py
      - ${data.models}model.pkl
      - ${data.processed}X_test.csv
      - ${data.processed}y_test.csv
